
server:
  port: 8001 #?????
spring:
  application:
    name: auth  #?????????????????????
  ################################################## JDBC ????  ##########################################
#  datasource:
#    username: root        #????????
#    password: root        #???????
#    url: jdbc:mysql://127.0.0.1:3306/bianchengbang_jdbc       #???url
#    driver-class-name: com.mysql.jdbc.Driver                  #?????
############################### ??? spring.config.import=configserver:##################
#  cloud:
#    config:
#      enabled: false
###################################### MyBatis ?? ######################################
#mybatis:
#  # ?? mapper.xml ???
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  #????????,?????????????? mapper.xml ??????????????
#  type-aliases-package: net.biancheng.c.entity
#  configuration:
#    #???????????????????
#    map-underscore-to-camel-case: true
########################################### Spring cloud ???????? ip ??###############################################
eureka:
  client: #??????? eureka ?????
    service-url:
      defaultZone: http://localhost:7001/eureka  #????? 7001????? application.yml ?????????? ?????
  instance:
    instance-id: spring-cloud-provider-8001 #?????????
    prefer-ip-address: true  #??????? ip ??
########################################## spring cloud ?? Spring Boot actuator ??????###################################
# Spring Boot 2.50? actuator ???????????????? heath ????????*????????????
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * ?yaml ???????????????
info:
  app.name: auth
  company.name: scumm
  build.artifactId: @project.artifactId@
  build.version: @project.version@